### ISSUE TITLE
CANCELLED: Wrong repo

### ISSUE THREAD

**Issue by HenrikBengtsson** [cran/qgcomp#1]
Erased: Meant to post to maintainers repo.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by HenrikBengtsson** [comment]
Thxs. Yeah, I noticed I created this issue in the wrong repo.  FWIW, https://github.com/alexpkeil1/qgcomp/issues/21.

BTW: Shouldn't 'Issues' be disabled for all repositories under https://github.com/cran/.
